---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: vstorage-slave-mds
  namespace: vstorage
  labels:
    app: vstorage
    daemon: mds
spec:
  template:
    metadata:
      labels:
        app: vstorage
        daemon: mds
    spec:
      nodeSelector:
        mds: slave
      volumes:
        - name: repo
          hostPath:
            path: /var/lib/vstorage
      containers:
        - name: vstorage-slave-mds
          image: vstorage:latest
          imagePullPolicy: IfNotPresent
          args: ["mds"]
          volumeMounts:
            - name: repo
              mountPath: /var/lib/vstorage
          ports:
            - containerPort: 2510
            - containerPort: 2511
          env:
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: vstorage-config
                  key: cluster.name
            - name: CLUSTER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: vstorage-config
                  key: cluster.password
            - name: SELF_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          livenessProbe:
              tcpSocket:
                port: 2510
              initialDelaySeconds: 30
              timeoutSeconds: 5
          readinessProbe:
              tcpSocket:
                port: 2510
              timeoutSeconds: 5
